### ISSUE TITLE
Critical Bug: Selecting a citation and then typing throws errors and breaks the editor

### ISSUE THREAD

**Issue by michael** [substance/lens#12] opened 2015-07-01 20:20 UTC

**Comment by obuchtala** [comment] 2015-07-01 20:51
Seems to be a regression of your work.
When typing over a selected citation it seems to be gone, but still you got in the state.

**Comment by obuchtala** [comment] 2015-07-01 20:55
Please take a look if there is a better solution to this problem.

**Comment by obuchtala** [comment] 2015-07-01 23:01
Closing for now, as it works for me.

**Closed as completed** 2015-07-02 13:35 UTC
Labels: bug
